# -*- coding: utf-8 -*-
"""project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lJc4hkR3_HORDsgvNIIZDmoudtNOX6m3
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix, classification_report, accuracy_score, precision_score, recall_score, f1_score
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from lightgbm import LGBMClassifier
from sklearn.naive_bayes import GaussianNB

df=pd.read_csv("/content/pcap.csv")

df = df.groupby('MalwareFamily', group_keys=False).apply( lambda x: x.sample( n=4000 if x.name == 'Benign' else min(len(x), 800),random_state=42 )).reset_index(drop=True)

df.info()

df.nunique()

"""df.sample(20, random_state=42)"""

df = df.drop(['Arch', 'Hash'], axis=1)

df.isnull().sum()

df['Variance'] = df['Variance'].fillna(df['Variance'].median())
df['Std'] = df['Std'].fillna(df['Std'].median())

df.isnull().sum()

df.shape

df.duplicated().sum()

df = df.drop_duplicates()

df['MalwareFamily'].value_counts()

df = df[df['MalwareFamily'] != 'Unknown']

import matplotlib.pyplot as plt

counts = df['MalwareFamily'].value_counts()
colors = ['black', 'blue', 'green', 'pink', 'purple', 'brown', 'orange']
plt.figure(figsize=(10,6))
bars = plt.bar(counts.index, counts.values, color=colors)

plt.title("Samples Count per Malware Family")
plt.xlabel("Malware Family")
plt.ylabel("Count")

plt.xticks(rotation=45)
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2,
             yval + 5,
             int(yval),
             ha='center')
plt.show()

df['Label'] = df['MalwareFamily'].apply(lambda x: 0 if x == 'Benign' else 1)

df['Label'].value_counts()

df = df.drop('MalwareFamily', axis=1)

df.info()

df.nunique()

df = df.drop(columns=[col for col in df.columns if df[col].nunique() <= 1])

df.info()

df.corr()['Label']

corr = df.corr(numeric_only=True)

target_corr = corr['Label'].abs().sort_values(ascending=False)

target_corr = target_corr.drop('Label')

plt.figure(figsize=(12,6))

bars = plt.bar(target_corr.index, target_corr.values)

plt.title("Correlation of Features with Label")
plt.xlabel("Features")
plt.ylabel("Correlation")

plt.xticks(rotation=90)

for bar in bars:
    yval = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width()/2,
        yval + 0.01,
        round(yval, 2),
        ha='center',
        fontsize=8
    )
plt.tight_layout()
plt.show()

threshold = 0.2

low_corr_features = target_corr[target_corr < threshold].index.tolist()


df = df.drop(columns=low_corr_features)

print("Deleted Columns:")
print(low_corr_features)

print("\nRemaining Columns:")
print(df.columns)

df.info()

df.shape

df['Label'].value_counts().plot.pie(autopct='%0.2f%%')

sns.countplot(x='Label', data=df)

import seaborn as sns
import matplotlib.pyplot as plt
plt.figure(figsize=(12,10))
top_features = df.corr()['Label'].sort_values(ascending=False).head(10).index
sns.heatmap(df[top_features].corr(), annot=True, cmap='coolwarm')
plt.show()

X = df.drop("Label", axis=1)
y = df["Label"]
X = X.replace([np.inf, -np.inf], np.nan)
imputer = SimpleImputer(strategy="median")
X = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

"""# ------------               RFC     ------------     """

Rmodel = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features="sqrt",
    bootstrap=True,
    random_state=42
)

Rmodel.fit(X_train, y_train)
y_pred = Rmodel.predict(X_test)
cmR = confusion_matrix(y_test, y_pred)

print("Confusion Matrix RFC:\n", cmR)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

disp = ConfusionMatrixDisplay(confusion_matrix=cmR, display_labels=[0,1])
disp.plot(cmap="Blues")
plt.show()

train_pred = Rmodel.predict(X_train)
print("Training Accuracy RFC:", accuracy_score(y_train, train_pred))
print("Testing Accuracy  RFC :", accuracy_score(y_test, y_pred))

"""

> # ------------               XGBOOST     ------------     

"""

grid_parameters = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.1, 0.01, 0.2],
    'max_depth': [3, 5, 7]
}


grid_model = GridSearchCV(
    XGBClassifier(random_state=0),
    grid_parameters,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)
grid_model.fit(X_train, y_train)
print("Best Parameters:", grid_model.best_params_)
print("Best Score:", grid_model.best_score_)
y_pred = grid_model.predict(X_test)


y_pred = grid_model.predict(X_test)
cmG = confusion_matrix(y_test, y_pred)

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)



print("Confusion Matrix XGBOOST:\n", cmG)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

disp = ConfusionMatrixDisplay(confusion_matrix=cmG, display_labels=[0,1])
disp.plot(cmap="Blues")
plt.show()

train_pred = grid_model.predict(X_train)
print("Training Accuracy XGBOOST:", accuracy_score(y_train, train_pred))
print("Testing Accuracy XGBOOST:", accuracy_score(y_test, y_pred))

"""# ------------               SVM     ------------     """

smodel = SVC(kernel='rbf', C=1.0, gamma='scale')
smodel.fit(X_train, y_train)
y_pred = smodel.predict(X_test)


CMS = confusion_matrix(y_test, y_pred)

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)


print("Accuracy SVM:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

disp = ConfusionMatrixDisplay(confusion_matrix=CMS, display_labels=[0,1])
disp.plot(cmap="Blues")
plt.show()

train_pred = smodel.predict(X_train)
print("Training Accuracy SVM:", accuracy_score(y_train, train_pred))
print("Testing Accuracy SVM:", accuracy_score(y_test, y_pred))

"""

------------               Logistic Regression    ------------     """

clf = LogisticRegression(max_iter=10000, random_state=0)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
train_pred = clf.predict(X_train)
CML = confusion_matrix(y_test, y_pred)

print("--- Logistic Regression Results ---")
print("Training Accuracy LR:", accuracy_score(y_train, train_pred))
print("Testing Accuracy LR:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
disp = ConfusionMatrixDisplay(confusion_matrix=CML, display_labels=[0,1])
disp.plot(cmap="Blues")
plt.show()

train_pred = clf.predict(X_train)
print("Training Accuracy LogisticRegression:", accuracy_score(y_train, train_pred))
print("Testing Accuracy LogisticRegression:", accuracy_score(y_test, y_pred))

"""# ------------               LightGBM    ------------

> Add blockquote


"""

GBMmodel = LGBMClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=-1,
    num_leaves=31,
    random_state=42
)

GBMmodel.fit(X_train, y_train)

y_pred = GBMmodel.predict(X_test)
CMGBM = confusion_matrix(y_test, y_pred)

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)


print("Accuracy  LightGBM:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

disp = ConfusionMatrixDisplay(confusion_matrix=CMGBM, display_labels=[0,1])
disp.plot(cmap="Blues")
plt.show()

train_pred = GBMmodel.predict(X_train)
print("Training Accuracy LightGBM:", accuracy_score(y_train, train_pred))
print("Testing Accuracy LightGBM:", accuracy_score(y_test, y_pred))

"""# ------------               Naïve Bayes ------------     """

nb_model = GaussianNB(
    var_smoothing=1e-10
)

nb_model.fit(X_train, y_train)
y_pred = nb_model.predict(X_test)

CMnb = confusion_matrix(y_test, y_pred)

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)


print("Accuracy  Naïve Bayes:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

disp = ConfusionMatrixDisplay(confusion_matrix=CMnb, display_labels=[0,1])
disp.plot(cmap="Blues")
plt.show()

train_pred = nb_model.predict(X_train)
print("Training Accuracy LightGBM:", accuracy_score(y_train, train_pred))
print("Testing Accuracy LightGBM:", accuracy_score(y_test, y_pred))

"""# download data"""

df.to_csv("sample_5000.csv", index=False)
from google.colab import files
files.download("sample_5000.csv")