# -*- coding: utf-8 -*-
"""progect2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VR8Iuw0WJnu5i-Du90oYSeZjhmQTHxfp
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.metrics import ConfusionMatrixDisplay, confusion_matrix, classification_report, accuracy_score, precision_score, recall_score, f1_score
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.datasets import load_breast_cancer
from sklearn.linear_model import LogisticRegression
from lightgbm import LGBMClassifier
from sklearn.naive_bayes import GaussianNB

df=pd.read_csv("/content/sample_5000.csv")

X = df.drop("Label", axis=1)
y = df["Label"]
X = X.replace([np.inf, -np.inf], np.nan)
imputer = SimpleImputer(strategy="median")
X = pd.DataFrame(imputer.fit_transform(X), columns=X.columns)
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y)

"""# ------------               poisoning    ------------     """

poisoning_rate = 0.04
n_poison = int(poisoning_rate * len(y_train))
poison_indices = np.random.choice(len(y_train), n_poison, replace=False)
y_train_poisoned = y_train.copy()
y_train_poisoned.iloc[poison_indices] = 1 - y_train_poisoned.iloc[poison_indices]

print(f"تم تسميم {n_poison} عينة في بيانات التدريب.")

"""# ------------               RFC     ------------     """

Rmodel = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features="sqrt",
    bootstrap=True,
    random_state=42
)

Rmodel.fit(X_train, y_train_poisoned)
y_pred = Rmodel.predict(X_test)
cmR = confusion_matrix(y_test, y_pred)

print("Confusion Matrix RFC:\n", cmR)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))


disp = ConfusionMatrixDisplay(confusion_matrix=cmR, display_labels=[0,1])
disp.plot(cmap="Blues")
plt.show()

train_pred = Rmodel.predict(X_train)
print("Training Accuracy RFC:", accuracy_score(y_train_poisoned, train_pred))
print("Testing Accuracy  RFC :", accuracy_score(y_test, y_pred))

"""> # ------------               XGBOOST     ------------     

"""

grid_parameters = {
    'n_estimators': [50, 100, 200],
    'learning_rate': [0.1, 0.01, 0.2],
    'max_depth': [3, 5, 7]
}


grid_model = GridSearchCV(
    XGBClassifier(random_state=0),
    grid_parameters,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)
grid_model.fit(X_train, y_train_poisoned)
print("Best Parameters:", grid_model.best_params_)
print("Best Score:", grid_model.best_score_)
y_pred = grid_model.predict(X_test)


y_pred = grid_model.predict(X_test)
cmG = confusion_matrix(y_test, y_pred)

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)



print("Confusion Matrix XGBOOST:\n", cmG)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

disp = ConfusionMatrixDisplay(confusion_matrix=cmG, display_labels=[0,1])
disp.plot(cmap="Blues")
plt.show()

train_pred = grid_model.predict(X_train)
print("Training Accuracy XGBOOST:", accuracy_score(y_train_poisoned, train_pred))
print("Testing Accuracy XGBOOST:", accuracy_score(y_test, y_pred))

"""# ------------ SVM ------------




"""

smodel = SVC(kernel='rbf', C=1.0, gamma='scale')
smodel.fit(X_train, y_train_poisoned)
y_pred = smodel.predict(X_test)


CMS = confusion_matrix(y_test, y_pred)

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)


print("Accuracy SVM:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

disp = ConfusionMatrixDisplay(confusion_matrix=CMS, display_labels=[0,1])
disp.plot(cmap="Blues")
plt.show()

train_pred = smodel.predict(X_train)
print("Training Accuracy SVM:", accuracy_score(y_train_poisoned, train_pred))
print("Testing Accuracy SVM:", accuracy_score(y_test, y_pred))

"""------------               Logistic Regression    ------------    """

clf = LogisticRegression(max_iter=10000, random_state=0)
clf.fit(X_train, y_train_poisoned)
y_pred = clf.predict(X_test)
train_pred = clf.predict(X_train)
CML = confusion_matrix(y_test, y_pred)

print("--- Logistic Regression Results ---")
print("Training Accuracy LR:", accuracy_score(y_train_poisoned, train_pred))
print("Testing Accuracy LR:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
disp = ConfusionMatrixDisplay(confusion_matrix=CML, display_labels=[0,1])
disp.plot(cmap="Blues")
plt.show()

train_pred = clf.predict(X_train)
print("Training Accuracy LogisticRegression:", accuracy_score(y_train_poisoned, train_pred))
print("Testing Accuracy LogisticRegression:", accuracy_score(y_test, y_pred))

"""# ------------               LightGBM    ------------


"""

GBMmodel = LGBMClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=-1,
    num_leaves=31,
    random_state=42
)

GBMmodel.fit(X_train, y_train_poisoned)

y_pred = GBMmodel.predict(X_test)
CMGBM = confusion_matrix(y_test, y_pred)

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)


print("Accuracy  LightGBM:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

disp = ConfusionMatrixDisplay(confusion_matrix=CMGBM, display_labels=[0,1])
disp.plot(cmap="Blues")
plt.show()

train_pred = GBMmodel.predict(X_train)
print("Training Accuracy LightGBM:", accuracy_score(y_train_poisoned, train_pred))
print("Testing Accuracy LightGBM:", accuracy_score(y_test, y_pred))

"""# ------------ Naïve Bayes ------------"""

nb_model = GaussianNB(
    var_smoothing=1e-10
)

nb_model.fit(X_train, y_train_poisoned)
y_pred = nb_model.predict(X_test)

CMnb = confusion_matrix(y_test, y_pred)

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)


print("Accuracy  Naïve Bayes:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

disp = ConfusionMatrixDisplay(confusion_matrix=CMnb, display_labels=[0,1])
disp.plot(cmap="Blues")
plt.show()

train_pred = nb_model.predict(X_train)
print("Training Accuracy LightGBM:", accuracy_score(y_train_poisoned, train_pred))
print("Testing Accuracy LightGBM:", accuracy_score(y_test, y_pred))